# Generated by Django 3.2.8 on 2021-11-09 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.TextField(max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('max_score', models.IntegerField(blank=True, default=100)),
                ('task_content', models.TextField(blank=True, max_length=5000)),
                ('tests_directory', models.TextField(blank=True, max_length=500)),
                ('tests_package', models.FileField(blank=True, upload_to='')),
                ('test_cmd', models.TextField(blank=True)),
                ('group', models.ManyToManyField(to='homework.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('git_repository_url', models.TextField(max_length=500)),
                ('hometask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homework.hometask')),
            ],
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True, max_length=5000)),
                ('passed', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('homework', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='homework.homework')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surname', models.TextField(max_length=500)),
                ('name', models.TextField(max_length=500)),
                ('group', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='homework.group')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='homework.student'),
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('student', 'hometask')},
        ),
    ]
