# Generated by Django 3.2.8 on 2021-11-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='number',
        ),
    ]
